name       : diorite
version    : 4.10.0
release    : 2
source     :
    - git|https://github.com/tiliado/diorite.git : a02cf3f55a9ad67f561c116d27f36ceeb36bbaa7
license    : BSD-2-Clause
component  : programming
summary    : Utility and widget library for Nuvola Player.
description: |
    Diorite library is a utility and widget library for Nuvola Player project based on GLib, GIO and GTK.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(python-2.7)
    - pkgconfig(sqlite3)
    - pyparsing
    - valadoc
setup      : |
    ./waf configure --prefix=/usr --libdir=%libdir% --mandir=/usr/share/man
build      : |
    ./waf build
install    : |
    ./waf install --destdir=$installdir
